services:
    webui-ros-joystick:
        image: husarion/webui-ros-joystick:noetic
        container_name: webui-ros-joystick
        network_mode: host
        command: roslaunch webui-ros-joystick webui.launch
